### ISSUE TITLE
it got detected on my anti virus

### ISSUE THREAD

**Issue by slade008** [The-Graze/WhoIsTalking#7]
It say the file named WS.reputation.1 is a threat

**Comment by Br0des** [comment]
Its the little to none downloads. Its safe

________________________________________
From: slade008 ***@***.***>
Sent: Monday, July 22, 2024 6:14:28 PM
To: The-Graze/WhoIsTalking
Cc: Subscribed
Subject: [The-Graze/WhoIsTalking] it got detected on my anti virus (Issue #7)

It say the file named WS.reputation.1 is a threat

**Comment by The-Graze** [comment]
First Stop using Norton360 its Junkass

WS.reputation.1 just means it's a new file and hasn't been downloaded much etc
you can see the code on here
